module RubyCvr
  class Constants
    KIND_OPTIONS = [
      { code: 10,  abbreviation: 'ENK',	description: 'Enkeltmandsvirksomhed' },
      { code: 15,	 abbreviation: 'PMV',	description: 'Personligt ejet Mindre Virksomhed' },
      { code: 20,	 abbreviation: 'DØD',	description: 'Dødsbo' },
      { code: 30,	 abbreviation: 'I/S',	description: 'Interessentskab' },
      { code: 40,	 abbreviation: 'K/S',	description: 'Kommanditselskab' },
      { code: 45,	 abbreviation: 'MSS',	description: 'Medarbejderinvesteringsselskab' },
      { code: 50,	 abbreviation: 'PAR',	description: 'Partrederi' },
      { code: 60,	 abbreviation: 'A/S',	description: 'Aktieselskab' },
      { code: 70,	 abbreviation: 'KAS',	description: 'Kommanditaktieselskab/Partnerselskab' },
      { code: 80,	 abbreviation: 'APS',	description: 'Anpartsselskab' },
      { code: 81,	 abbreviation: 'IVS',	description: 'Iværksætterselskab' },
      { code: 90,	 abbreviation: 'FON',	description: 'Fonde og andre selvejende institutioner' },
      { code: 100, abbreviation: 'EFO',	description: 'Erhvervsdrivende fond' },
      { code: 110, abbreviation: 'FOR',	description: 'Forening' },
      { code: 115, abbreviation: 'FFO',	description: 'Frivillig forening' },
      { code: 130, abbreviation: 'ANS',	description: 'Andelsselskab (-forening)' },
      { code: 140, abbreviation: 'ABA',	description: 'Andelsselskab (-forening) med begrænset ansvar' },
      { code: 150, abbreviation: 'FBA',	description: 'Forening eller selskab med begrænset ansvar' },
      { code: 151, abbreviation: 'SMA',	description: 'Selskab med begrænset ansvar' },
      { code: 152, abbreviation: 'FMA',	description: 'Forening med begrænset ansvar' },
      { code: 160, abbreviation: 'EØF',	description: 'Europæisk Økonomisk Firmagruppe' },
      { code: 170, abbreviation: 'FAS',	description: 'Filial af udenlandsk aktieselskab, kommanditakties' },
      { code: 180, abbreviation: 'FAP',	description: 'Filial af udenlandsk anpartsselskab eller selskab' },
      { code: 190, abbreviation: 'FBA',	description: 'Filial af udenlandsk virksomhed med begrænset ansv' },
      { code: 195, abbreviation: 'SCE',	description: 'SCE-selskab' },
      { code: 196, abbreviation: 'FSC',	description: 'Filial af udenlandsk SCE-selskab' },
      { code: 200, abbreviation: 'FUV',	description: 'Filial af anden udenlandsk virksomhedsform' },
      { code: 210, abbreviation: 'UDL',	description: 'Anden udenlandsk virksomhed' },
      { code: 220, abbreviation: 'FEØ',	description: 'Fast forretningssted af Europæisk økonomisk Firmag' },
      { code: 230, abbreviation: 'STA',	description: 'Statslig administrativ enhed' },
      { code: 235, abbreviation: 'SOV',	description: 'Selvstændig offentlig virksomhed' },
      { code: 245, abbreviation: 'REG',	description: 'Region' },
      { code: 250, abbreviation: 'KOM',	description: 'Primærkommune' },
      { code: 260, abbreviation: 'FKI',	description: 'Folkekirkelige Institutioner' },
      { code: 270, abbreviation: 'EUO',	description: 'Enhed under oprettelse i Erhvervsstyrelsen' },
      { code: 280, abbreviation: 'ØVR',	description: 'Øvrige virksomhedsformer' },
      { code: 285, abbreviation: 'FIV',	description: 'Særlig finansiel virksomhed' },
      { code: 290, abbreviation: 'E/S',	description: 'SE-selskab' },
      { code: 291, abbreviation: 'FES',	description: 'Filial af SE-selskab' },
      { code: 990, abbreviation: 'UOP',	description: 'Uoplyst virksomhedsform' },
    ]
  end
end
